package com.banque.abc.tpe.entity.enums;

public enum TypePanne {
    COURT_CIRCUIT,
    DEFAUT_ISOLEMENT,
    SURCHARGE,
    COUPURE_SECTEUR,
    RUPTURE_USURE_PIECES,
    DEFAUT_LUBRIFICATION,
    GRIPPAGE,
    HARDWARE,
    SOFTWARE,
    INCIDENT_0044_0088,
    INCIDENT_0060_CENTRE_BANCAIRE_NON_ATTEINT,
    INCIDENT_001,
    INCIDENT_0074,
    INCIDENT_020E_0067,
    INCIDENT_0050,
    ALERTE_IRRUPTION,
    PROBLEME_BATTERIE_CHARGE,
    IMPRIMANTE_BLOQUEE,
    INCIDENT_0060_ERREUR_CARTE,
    ERREUR_SAISIE_PIN
}
